### ISSUE TITLE
Want to know why?

### ISSUE THREAD

**Issue by ExFly** [jonatasbaldin/ignore#19]
I want to know the purpose of this project. Because there are already other projects in progress, you can actually fork some code and then enhance the functionality yourself.

[gitignore.io](https://github.com/joeblau/gitignore.io) and [there](https://www.gitignore.io/)

If no reason，Don't repeat the wheel

**Comment by jonatasbaldin** [comment]
Hey there :)

This is my first project in Golang, and I'm using it as a learning experiment. So far, I've received some awesome PRs, improving the library, teaching me more about idiomatic Go and what the language can do.

Please, don't be rude over the Internet like this. Repeating the wheel sometimes is necessary for learning - we all made `hello worlds` and `todo lists` at some point in time.

Cheers 🎉
