### ISSUE TITLE
Deploy ignore into package managers

### ISSUE THREAD

**Issue by jonatasbaldin** [jonatasbaldin/ignore#2]
Let's put ignore everywhere!

- [ ] brew
- [ ] apt
- [ ] nuget 
- [ ] <what's the one you use? let's add here!>

**Comment by avelino** [comment]
split to N issue

**Comment by vdemario** [comment]
Suggestion: use [goreleaser](https://github.com/goreleaser/goreleaser).

**Comment by jonatasbaldin** [comment]
Thanks for the suggestions @avelino and @vdemario. I'll open separated issues and link this one there.
