### ISSUE TITLE
Add mod or dep support?

### ISSUE THREAD

**Issue by exfly** [jonatasbaldin/ignore#5]

**Comment by jonatasbaldin** [comment]
Can you explain a bit? I'm not super into Go, this is my first project :)

**Comment by vdemario** [comment]
It means dependency management with either [dep](https://golang.github.io/dep/) or [modules](https://github.com/golang/go/wiki/Modules).

**Comment by jonatasbaldin** [comment]
Thanks :) Added a review on the PR

**Comment by faabiosr** [comment]
I created the #22 for this issue.
